# Generated by Django 5.2.7 on 2025-10-20 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre_comercial', models.CharField(blank=True, max_length=255, null=True)),
                ('Imagen_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='on_premise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('version', models.CharField(max_length=50)),
                ('fecha_instalacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_de_compra', models.DateTimeField()),
                ('fecha_sin_soporte', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('tipo_letra', models.CharField(max_length=100)),
                ('enum_tema', models.CharField(choices=[('CLARO', 'Claro'), ('OSCURO', 'Oscuro'), ('AUTOMATICO', 'Automatico')], default='CLARO', max_length=10)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_Empresa.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('enum_plan', models.CharField(choices=[('BASICO', 'Básico'), ('PREMIUM', 'Premium'), ('EMPRESARIAL', 'Empresarial')], default='BASICO', max_length=15)),
                ('enum_estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=15)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_Empresa.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='PagoSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_proximo_pago', models.DateTimeField()),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Empresa.suscripcion')),
            ],
        ),
    ]
