# Generated by Django 5.2.7 on 2025-10-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='on_premise',
            name='fecha_de_compra',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
