# Generated by Django 5.2.7 on 2025-11-05 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacion',
            name='id_cliente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_Cliente.cliente'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='id_cliente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_Cliente.cliente'),
        ),
        migrations.AddField(
            model_name='garante',
            name='id_domicilio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_Cliente.domicilio'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='id_cliente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_Cliente.cliente'),
        ),
    ]
