# Generated by Django 5.2.7 on 2025-10-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiluser',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
