# Generated by Django 5.2.7 on 2025-10-20 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_Cliente', '0001_initial'),
        ('app_Empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('monto_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monto_Solicitado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enum_estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('SOLICITADO', 'SOLICITADO'), ('DESENBOLSADO', 'DESENBOLSADO'), ('FINALIZADO', 'FINALIZADO')], default='Pendiente', max_length=20)),
                ('Numero_Cuotas', models.IntegerField()),
                ('Monto_Cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Moneda', models.CharField(max_length=10)),
                ('Tasa_Interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Fecha_Aprobacion', models.DateField(blank=True, null=True)),
                ('Fecha_Desembolso', models.DateField(blank=True, null=True)),
                ('Fecha_Finalizacion', models.DateField(blank=True, null=True)),
                ('Monto_Pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Cliente.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Empresa.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Credito.tipo_credito')),
            ],
        ),
        migrations.CreateModel(
            name='Ganancia_Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_prestado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duracion_meses', models.IntegerField()),
                ('ganacia_esperada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Cliente.cliente')),
                ('Credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Credito.credito')),
            ],
        ),
    ]
